import {
  NEST_CLI_PACKAGE_NAME,
  NEST_CLI_VERSION,
  NEST_COMMON_PACKAGE,
  NEST_CORE_PACKAGE,
  NEST_PLATFORM_EXPRESS_PACKAGE,
  NEST_SCHEMATICS_PACKAGE_NAME,
  NEST_SCHEMATICS_VERSION,
  NEST_TESTING_PACKAGE,
  NEST_VERSION,
} from './nest-version.js';

export const REFLECT_METADATA_PACKAGE = 'reflect-metadata';
export const RXJS_PACKAGE = 'rxjs';

export const REFLECT_METADATA_VERSION = '^0.2.2';
export const RXJS_VERSION = '^7.8.1';

export const nestRuntimeDependencies = Object.freeze({
  [NEST_COMMON_PACKAGE]: NEST_VERSION,
  [NEST_CORE_PACKAGE]: NEST_VERSION,
  [NEST_PLATFORM_EXPRESS_PACKAGE]: NEST_VERSION,
  [REFLECT_METADATA_PACKAGE]: REFLECT_METADATA_VERSION,
  [RXJS_PACKAGE]: RXJS_VERSION,
} as const);

export const nestDevDependencies = Object.freeze({
  [NEST_CLI_PACKAGE_NAME]: NEST_CLI_VERSION,
  [NEST_SCHEMATICS_PACKAGE_NAME]: NEST_SCHEMATICS_VERSION,
  [NEST_TESTING_PACKAGE]: NEST_VERSION,
} as const);
