name: Feature CI
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  pull_request:
    branches: [feat/**]

permissions:
  actions: read
  contents: read

concurrency:
  group: feature-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  feature-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - run: corepack enable

      - run: yarn dlx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable
      - uses: nrwl/nx-set-shas@v4

      - run: yarn nx-cloud record -- yarn nx format:check
      - run: yarn nx affected -t lint test build typecheck --exclude "$(yarn nx show projects | grep -- '-e2e$' | paste -sd, -)"
      - run: yarn nx fix-ci
        if: always()
