name: Main CI
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read

concurrency:
  group: main-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - run: corepack enable

      - run: yarn dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - run: yarn install --immutable
      - uses: nrwl/nx-set-shas@v4

      - run: yarn nx affected -t build e2e-ci
      - run: yarn nx fix-ci
        if: always()
